Mongo driver update. Improved Error Handling for pipeline() based operations. Error reporting improvements
YadamuDBI: All Drivers - Capture First and Latest Exceptions generated by the Database
DBReader: Capture Exceptions during _read operations
PostgressDBI: Added await operator to  this.executeSQL calls in confgureConnection()
YadamuWriter: Added column count check
YadamuWriter: Centralized handling of INSERT MANY and INSERT ONE Exception Handling
OracleWriter: Simplifed handling of Pending LOB objects during batch and iterative write operations
OracleWriter: Fixederror reporting when row contains one or more LOB values
YadamuLogger: Separate Data values from Stack Trace when logging INSERT MANY and INSERT ONE Errors
YadamuLogger: Use DBWriter, FileDBI to write data values as YADAMU export file.
DBReader: Simplify Constructor, obtain mode and status from DBI
DBWriter: Simplify Constructor, obtain mode and status from DBI
FileDBI: Ensure streams are properly closed on finalize()
OracleError: Obfuscate data values in Bind arguments
YadamuRejectManager: Use FileDBI interface to create and write files
MongoDBI: New Data Type mapping algorithm based on BSON types and the Mongodb aggregation framework. Prevent 0 length Strings
MongoDBI: Mongo Roundtrip testing and fixes
YadamuDBI: All Drivers -Added mappings for MongoDB BSON data types
YadamuDBI: All Drivers - Standardized save point name
YadamuDBI: All Drivers - Improved error message generation
YadamuDBI: Fixed setting of worker tag in SQL Trace
YadamuWriter: Report Batch Error before reverting to save point
MsSQLDBI: Added length argument when using binary data type in bulk insert operation
MssQLDBI: Added class MsSQLReader() which wraps the mssql streaming request.query() interface in a true "Readable".
MsSQLDBI: Clear cached Prepared Statement before performing a Rollback operation. Avoid "Can't rollback transaction. There is a request in progress."
MsSQLDBI: Replacef getInputStream() 'Hack' with MsSQLReader()
SnowflakeDBI: Added class SnowflakeReader() which wraps the mssql streaming request.query() interface in a true "Readable".
SnowflakeDBI: Replaced getInputStream() 'Hack' with SnowflakeReader()
ExampleDBI: Added class ExampleReader() which is used when a database does  support returning a result set as a Readable
ExampleDBI: Replaced getInputStream() 'Hack' withExampleReader()
MsSQLQA: Fixed import for MsSQLError()
OracleQA: Fixed import for OracleError()
YadamuWriter: Include skipTable in pending rows check
YadamuWriter: Incldue skipTable in batch complete check
dbReader: Rework abortTable logic