Revised Logic for building export Pipelines on change of table. Revised Error and Lost Connection Handling for Parallel Mode operations
DBReader: [Export]: Revised logic for rebuilding pipeline on change of table
DBReaderParallel: Terminate Parallel operations on abort
DBWriter: Remove redundant function abortTable()

Yadamu: Add a timeout to the Unhandled Rejection Process Termination. Allow the process to terminate normally before killing it
YadamuError: Refactor as YadamuException. Refactor subclasses
YadauuErrror: Add a static method to determine if an exception is caused by a lost database connection
YadamuWriter: Revise Exception Handling logic
FileDBI: Remove redundant class TableManager:
OracleDBI: Cleanup lost connection handling when recreating triggers, constraints and materialized views
AWSS3DBI: Wait for all write operations to complete before calling finalize()

YadamuQA: [LostConnection]: Updated test configuration
YadamuQA: Add LOADER, AWSS3 and Azure to standard regression test
OracleQA: Return notes as CLOB  rather than VARCHAR2(4000)
AzureQA: Ensure Target Container exists in recreateSchema()