Centralized Connection Management. MsSQL UTF8 Support.  Oracle JSON and XML Storage options
MsSQL: Add Support for specifying Collation
MsSQL: Map TEXT to NVARCHAR(MAX) when using UTF8 Collation
Oracle: YADAMU_FEATURE_DETECTION supports for Oracle Manage Services
Oracle: YADAMU_FEATURE_DETECTION detects default XML Storage Model
Oracle: Specify WELLFORMED flag when parsing XML Values
Oracle: Support XMLType store as BINARY
Oracle: Support JSON store as BLOB, CLOB, VARCHAR2 and Native JSON
DBReader: Enhanced Event Handling during Pipe based copy Operations
DBReaderMaster: Refactor creation of copy operations
DBWriter: Standardize Reporting of Read and Write operations
DBWriter: Refactor skipTable Flag. Move from dbWrtiter class to tableWriter class
DBWriter: Refactor commit and rollback operations to tableWriter class
YadamuDBI: Refactor Reject Manager: Move from YadamuDBI class to Yadamu class
YadamuDBI: Generalized support for reconnecting in the event of connection failure
MySQLDBI: Do not start keep-alive if READ_KEEP_ALIVE is 0
YadamuError: Identify  "lost connection" errors
YadamuWriter: Centralize tracking of rows cached, written, skipped and committed
YadamuWriter: Refactor statistics tracking. Add getStatistics() method.
MariaDBI: Support centralized management of lost connections
OracleDBI: Support centralized management of lost connections
MySQLDBI: Support centralized management of lost connections
MsSQLDBI: Support centralized management of lost connections
PostgresDBI: Support centralized management of lost connections
MsSQLDBI: Revise stagingTable and dbFileloader classes to use new MsSQLDBI methods
MsSQLDBI: Enhanced driver interface
MsSQLDBI: Add ServerProperties to systemInformation
MsSQLDBI: Add DatabaseProperties to systemInformation
MsSQLDBI: Refactor prepared statement handlings from tableWriter class to MsSQLDBI class
OracleDBI: Added  freeIinputStream() method to avoid errors when close() event takes place after connection is closed
DBWriter: Support ABORT,SKIP and FLUSH options when inputStream raises exceptions